### PR TITLE
Add parameter alignment rule

### PR DESCRIPTION
**Pull request by mcnelson**
This arose in one of my PRs so please discuss. I would favor aligning the parameters of a method call since it looks nice.

### CODE REVIEW

**Comment by jmdeldin** [comment]
1. Could you add some examples?
1. Where do you add the terminating paren? New line aligned with method call or after the last argument?
1. Do you break the arguments at one per line? Can Rubocop support this?
1. How do you envision handling the case of positional arguments and hashes spanning multiple lines? For example:

```ruby
foo(some_long_variable_name,
    some_other_variable_name,
    includes: {some_model: {some_other_model: something_else},
               garbage: trash
              })

**Comment by civrot** [comment]
Please use the 'Prefer....` style and group it with those.

**Comment by civrot** [comment]
Examples would be boss.

**Comment by civrot** [comment]
What do we want to do with this?

**Comment by civrot** [comment]
*cough*

**Comment by civrot** [comment]
Delete?

**Comment by civrot** [comment]
Delete?

**Comment by civrot** [comment]
Beuller?

**Comment by civrot** [comment]
Hello? @TheClymb/developers

**Comment by jmdeldin** [comment]
This must be about wizards. @mcnelson ...

...

...

...

.

**Comment by civrot** [comment]
CLOSING

**Comment by maxjustus** [comment]
COMMENTING

**Comment by maxjustus** [comment]
comment

**Pull request closed without merging**
