### PR TITLE
Capitalize SQL Statements?

### PR DESCRIPTION
**Pull request by civrot**
Discuss.

I don't really have a strong opinion on this. @mcnelson made a [commont on one of my PRs](https://github.com/TheClymb/theclymb/pull/4068/files#r24545508).
Opening it up for discussion.

### CODE REVIEW

**Comment by mcnelson** [comment]
Double check your PR title. Also, perhaps we need a new SQL style markdown file rather than adding this to the rails one.

**Comment by civrot** [comment]
Oops ;-0

I was thinking that we would have a rails specific one since SQL in a rails app may not be a full and/or a  valid SQL statement,

**Comment by civrot** [comment]
@maxjustus @mcnelson ?

**Comment by jmdeldin** [comment]
+1 for capitalizing

I use lowercase for writing ad-hoc queries in console, but I always use uppercase for committed code. I think it makes it a lot nicer to easily distinguish SQL from AR when quickly glancing through code.

**Comment by civrot** [comment]
So we are all for always capitalizing SQL statements?

**Comment by jmdeldin** [comment]
@maxjustus is the last one to chime in, and he might just be the wild card.

**Comment by hexgnu** [comment]
https://twitter.com/mjkirk/status/451434255328243712

**Comment by civrot** [comment]
Thats kind of how I feel about capitalized SQL...but there are other battles worse fighting

**Comment by jmdeldin** [comment]
IT MAKES YOU MORE THOUGHTFUL.

**Comment by jmdeldin** [comment]
+1

**Comment by civrot** [comment]
@maxjustus  you want to pipe in....(you want lower case, right)

**Comment by civrot** [comment]
I am assuming since @maxjustus has not piped in that he agrees with me. So it sounds like we are in a stalemate.  @slnovak do you have an opinion?

**Comment by mcnelson** [comment]
+1

**Pull request merged**
