### PR TITLE
Define guides for spaces aroung things.

### PR DESCRIPTION
**Pull request by civrot**
Spurred on by a [PR Comment](https://github.com/TheClymb/theclymb/pull/4068/files#r24543552).

The changes in this PR differ from the opinion expressed in the PR referenced above.

Discuss

### CODE REVIEW

**Comment by civrot** [comment]
Anyone?

**Comment by civrot** [comment]
@maxjustus @mcnelson ?

**Comment by jmdeldin** [comment]
I like what you've written for the guide, although I wonder if we should clarify that it's not spaces around curly braces, but spaces for one-line, curly-brace block calls.

**Comment by civrot** [comment]
As opposed to multiline blocks?  There are already spaces surrounding them, no?

**Comment by jmdeldin** [comment]
Sorry, as opposed to doing `%w{ foo }` or `%r{ \w+ }`, we would omit spaces and just do `%w{foo}`, for example.

**Comment by civrot** [comment]
To me,  `%w{ foo }` looks cleaner than `%w{foo}`, but `foo(arg)` over `foo( arg )` any day.

**Comment by civrot** [comment]
@mcnelson @maxjustus @slnovak you guys want to through in your opinion?

**Comment by mcnelson** [comment]
Agree with `blah.map { |a| a.something }`, disagree with `%w{ blah something }`.

**Comment by civrot** [comment]
spacing
https://github.com/bbatsov/ruby-style-guide#spaces-operators  _(this is what rubocop is based on)_

**Comment by civrot** [comment]
@maxjustus @slnovak you guys want to through in your opinion?

**Comment by maxjustus** [comment]
I think I prefer `{ x: 1 }` to `{x: 1}`. I also prefer `%w{foo}` to `%w{ foo }`

**Comment by slnovak** [comment]
I'll give a +1 to `%w{ foo bar baz }`. 

I also prefer `{ one: 1, two: 2 }' since it makes it consistent to have two-space indenting if having a multi-line hash:

```ruby
def foo
  { one: 1
    two: 2
    three: 3 }
end
```

**Comment by civrot** [comment]
I agree, can someone take on the role of reviewer for this one please. @TheClymb/developers

**Comment by jmdeldin** [comment]
I think I'm lost in the discussion now. So are we enforcing spaces around hashes? Even in one-liners, like Rails helpers (e.g., `link_to 'thing', somewhere_url, html_options: { class: 'important' }`)?

**Comment by civrot** [comment]
Thats my vote.

**Comment by jmdeldin** [comment]
How do you want to handle this part of the guide then?

> Avoid spaces between braces and key value pairs when nesting hashes. {a: {b: 1}}, not { a: { b: 1 } }

I can go either way. I like spaces for hashrockets but avoid them for one-liners. Coming from Perl, I like spaces after operators but had that beaten out of me joining our team, so I don't know what to believe anymore.

**Comment by civrot** [comment]
Change it to match these rules. I did not see those before.

**Comment by civrot** [comment]
I am going to merge this tomorrow and update rubocop if there are no further comments

**Pull request merged**
